metabolism:
  solver: glpk
  objective: BIOMASS

  # === Environmental constraints (already in place) ===
  metabolite_map:
    C0001: EX_C0001_e
    C0002: EX_C0002_e
    C0003: EX_C0003_e
    C0004: EX_C0004_e
    C0005: EX_C0005_e
    C0006: EX_C0006_e
    C0007: EX_C0007_e
    C0008: EX_C0008_e
    C0009: EX_C0009_e
    C0010: EX_C0010_e

  uptake:
    mode: linear_clip          # linear_clip | linear | cap_only
    mM_per_uptake: 1.0
    max_uptake: 10.0
    secretion_upper: 1000.0

  transcription:
    mode: eflux                # eflux | threshold
    threshold_TPM: 10          # used by threshold
    eflux_norm: max            # max | percentile
    percentile: 95             # used when eflux_norm: percentile
    min_scale: 0.0             # floor scaling for low expression (0 = full shutoff)
